services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  players-wallet-service:
    build:
      context: .
      dockerfile: PlayersWallet.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis

volumes:
  redis_data: